-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/6hyZIt
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE IF NOT EXISTS "Film" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(255)   NOT NULL,
    "description" varchar(200),
    "releaseDate" date,
    "duration" int,
    "rating_id" int,
    CONSTRAINT "pk_Film" PRIMARY KEY (
        "id"
     )
);

CREATE TABLE IF NOT EXISTS "Rating" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(10)   NOT NULL,
    CONSTRAINT "pk_Rating" PRIMARY KEY (
        "id"
     ),
    CONSTRAINT "uc_Rating_name" UNIQUE (
        UPPER("name")
    )
);

CREATE TABLE IF NOT EXISTS "Genre" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50)   NOT NULL,
    CONSTRAINT "pk_Genre" PRIMARY KEY (
        "id"
     ),
    CONSTRAINT "uc_Genre_name" UNIQUE (
        UPPER("name")
    )
);

CREATE TABLE IF NOT EXISTS "FilmGenre" (
    "film_id" int   NOT NULL,
    "genre_id" int   NOT NULL
);

CREATE TABLE IF NOT EXISTS "User" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" varchar(255)   NOT NULL,
    "login" varchar(20)   NOT NULL,
    "name" varchar(255)   NULL,
    "birthday" date,
    CONSTRAINT "pk_User" PRIMARY KEY (
        "id"
     ),
    CONSTRAINT "uc_User_email" UNIQUE (
        UPPER("email")
    ),
    CONSTRAINT "uc_User_login" UNIQUE (
        UPPER("login")
    )
);

CREATE TABLE IF NOT EXISTS "FilmLike" (
    "film_id" int   NOT NULL,
    "user_id" int   NOT NULL
);

CREATE TABLE IF NOT EXISTS "FriendShip" (
    "user_id" int   NOT NULL,
    "friend_id" int   NOT NULL,
    "confirm" boolean  DEFAULT 'false' NOT NULL
);

ALTER TABLE "Film" ADD CONSTRAINT "fk_Film_rating_id" FOREIGN KEY("rating_id")
REFERENCES "Rating" ("id");

ALTER TABLE "FilmGenre" ADD CONSTRAINT "fk_FilmGenre_film_id" FOREIGN KEY("film_id")
REFERENCES "Film" ("id");

ALTER TABLE "FilmGenre" ADD CONSTRAINT "fk_FilmGenre_genre_id" FOREIGN KEY("genre_id")
REFERENCES "Genre" ("id");

ALTER TABLE "FilmLike" ADD CONSTRAINT "fk_FilmLike_film_id" FOREIGN KEY("film_id")
REFERENCES "Film" ("id");

ALTER TABLE "FilmLike" ADD CONSTRAINT "fk_FilmLike_user_id" FOREIGN KEY("user_id")
REFERENCES "User" ("id");

ALTER TABLE "FriendShip" ADD CONSTRAINT "fk_FriendShip_user_id" FOREIGN KEY("user_id")
REFERENCES "User" ("id");

ALTER TABLE "FriendShip" ADD CONSTRAINT "fk_FriendShip_friend_id" FOREIGN KEY("friend_id")
REFERENCES "User" ("id");

CREATE INDEX IF NOT EXISTS "idx_FriendShip_user_id"
ON "FriendShip" ("user_id");

CREATE INDEX IF NOT EXISTS "idx_FriendShip_friend_id"
ON "FriendShip" ("friend_id");

INSERT INTO "Rating" (name) VALUES ('GA'),('PG'),('PG-13'),('R'),('NC-17');
