CREATE TABLE IF NOT EXISTS ratings
(
    "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(10) NOT NULL,
    CONSTRAINT pk_ratings PRIMARY KEY (
                                       "id"
        ),
    CONSTRAINT uc_ratings_name UNIQUE (
                                       "name"
        )
);
INSERT INTO ratings (name)
VALUES ('GA'),
       ('PG'),
       ('PG-13'),
       ('R'),
       ('NC-17');