CREATE TABLE IF NOT EXISTS films (
                                     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "name" varchar(255) NOT NULL,
                                     "description" varchar(200),
                                     "release_date" date,
                                     "duration" int,
                                     "rating_id" int,
                                     CONSTRAINT pk_films PRIMARY KEY ("id")
);
CREATE TABLE IF NOT EXISTS ratings (
                                       "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "name" varchar(10) NOT NULL,
                                       CONSTRAINT pk_ratings PRIMARY KEY ("id"),
                                       CONSTRAINT uc_ratings_name UNIQUE ("name")
);
CREATE TABLE IF NOT EXISTS genres (
                                      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "name" varchar(50) NOT NULL,
                                      CONSTRAINT pk_genres PRIMARY KEY ("id"),
                                      CONSTRAINT uc_genres_name UNIQUE ("name")
);
CREATE TABLE IF NOT EXISTS film_genres (
                                           "film_id" int NOT NULL, "genre_id" int NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
                                     "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "email" varchar(255) NOT NULL,
                                     "login" varchar(20) NOT NULL,
                                     "name" varchar(255) NULL,
                                     "birthday" date,
                                     CONSTRAINT pk_users PRIMARY KEY ("id"),
                                     CONSTRAINT uc_users_email UNIQUE ("email"),
                                     CONSTRAINT uc_users_login UNIQUE ("login")
);
CREATE TABLE IF NOT EXISTS film_likes (
                                          "film_id" int NOT NULL, "user_id" int NOT NULL
);
CREATE TABLE IF NOT EXISTS friendships (
                                           "user_id" int NOT NULL,
                                           "friend_id" int NOT NULL,
                                           "confirm" boolean DEFAULT 'false' NOT NULL,
                                           CONSTRAINT uc_users_friends UNIQUE ("user_id", "friend_id")
);
ALTER TABLE
    films
    ADD
        CONSTRAINT IF NOT EXISTS fk_films_rating_id FOREIGN KEY ("rating_id") REFERENCES ratings ("id");
ALTER TABLE
    film_genres
    ADD
        CONSTRAINT IF NOT EXISTS fk_film_genres_film_id FOREIGN KEY ("film_id") REFERENCES films ("id");
ALTER TABLE
    film_genres
    ADD
        CONSTRAINT IF NOT EXISTS fk_film_genres_genre_id FOREIGN KEY ("genre_id") REFERENCES genres ("id");
ALTER TABLE
    film_likes
    ADD
        CONSTRAINT IF NOT EXISTS fk_film_likes_film_id FOREIGN KEY ("film_id") REFERENCES films ("id");
ALTER TABLE
    film_likes
    ADD
        CONSTRAINT IF NOT EXISTS fk_film_likes_user_id FOREIGN KEY ("user_id") REFERENCES users ("id");
ALTER TABLE
    friendships
    ADD
        CONSTRAINT IF NOT EXISTS fk_friendships_user_id FOREIGN KEY ("user_id") REFERENCES users ("id");
ALTER TABLE
    friendships
    ADD
        CONSTRAINT IF NOT EXISTS fk_friendships_friend_id FOREIGN KEY ("friend_id") REFERENCES users ("id");
CREATE INDEX IF NOT EXISTS idx_friendships_user_id ON friendships ("user_id");
CREATE INDEX IF NOT EXISTS idx_friendships_friend_id ON friendships ("friend_id");
